# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura L. Theis
email: theis.laura.l@gmail.com
description: a blog about learning to code and relationships with other learning
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.the-is.com # the base hostname & protocol for your site
permalink: /blog/:categories/:year/:month/:day/:title.html
github_username:  lltheis
timezone: America/Boise

# Build settings
markdown: kramdown
kramdown:
  input: GFM
port: 3000
host: 0.0.0.0

exclude: ['Gemfile',
          'Gemfile.lock']
